spring:
  profiles: local,local-will

cloud:
  aws:
    s3:
      bucket: local-embedded-bucket
      mock:
        port: 5050
      region:
        static: ap-northeast-2
      stack:
        auto: false

